version: "3.9"

services:
  db:
    image: postgres:16
    container_name: PostgreSQL
    restart: always
    #env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes: # docker-entrypoint-initdb works only once during initialization of the container
      - postgres_data:/var/lib/postgresql/data
      - ./db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql 
      - ./db/2_indexes.sql:/docker-entrypoint-initdb.d/2_indexes.sql
      - ./db/3_initial_insert.sql:/docker-entrypoint-initdb.d/3_initial_insert.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]  
      interval: 10s
      timeout: 10s 
      retries: 5  

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: PGAadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      

  etl:
    build: ./etl
    container_name: etl
    env_file: .env
    depends_on:
      - db

  model:
    build: ./model
    container_name: campaign_model
    env_file: .env
    depends_on:
      - db

  api:
    build: ./api
    container_name: campaign_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - model

  app:
    build: ./app
    container_name: campaign_app
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - api

volumes:
  postgres_data:
  pgadmin_data:
