services:

  db:
    image: postgres:17
    container_name: PostgreSQL
    restart: always
    env_file: campx/.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./campx/db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./campx/db/2_indexes.sql:/docker-entrypoint-initdb.d/2_indexes.sql
      - ./campx/db/3_initial_insert.sql:/docker-entrypoint-initdb.d/3_initial_insert.sql
      - ./campx/db/4_views.sql:/docker-entrypoint-initdb.d/4_views.sql
      - ./campx/db/5_stored_procedures.sql:/docker-entrypoint-initdb.d/5_stored_procedures.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: PGAadmin
    restart: always
    env_file: campx/.env
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      

  # ── DATA SCIENCE ──────────────────────────────────────
  # Owner: Davit Badalyan
  # Runs ETL then simulation sequentially — exits when done
  ds:
    build: ./campx/ds
    container_name: campaign_ds
    env_file: campx/.env
    volumes:
      - ./campx/api/SQLHandler.py:/app/SQLHandler.py
      - ./campx/api/db_interactions.py:/app/db_interactions.py
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  backend:
    build: ./campx/api
    container_name: backend
    ports:
      - "8000:8000"
    env_file: campx/.env
    volumes:
      - ./campx/api/SQLHandler.py:/app/SQLHandler.py
      - ./campx/api/db_interactions.py:/app/db_interactions.py
    depends_on:
      db:
        condition: service_healthy
    restart: always

# ── FRONTEND ──────────────────────────────────────────
  # Owner: Armine Babajanyan
  front:
    build: ./campx/app
    container_name: front
    ports:
      - "8501:8501"
    env_file: campx/.env
    environment:
      API_URL: http://backend:8000
    depends_on:
      - backend
    restart: always

  # prefect:
  #   image: prefecthq/prefect:2-latest
  #   container_name: campaign_prefect
  #   command: prefect server start --host 0.0.0.0
  #   ports:
  #     - "4200:4200"
  #   environment:
  #     PREFECT_UI_API_URL: http://localhost:4200/api
  #   volumes:
  #     - prefect_data:/root/.prefect
  #   restart: always

  # orchestration:
  #     build: ./campx/orchestration
  #     container_name: campaign_orchestration
  #     env_file: campx/.env
  #     environment:
  #       PREFECT_API_URL: http://prefect:4200/api
  #     depends_on:
  #       - db
  #     restart: "no"

volumes:
  postgres_data:
  pgadmin_data:
  #prefect_data:
